labels:
  - name: ':robot: Renovate'
    description: 'Renovate による依存関係の更新'
    color: '0052CC'
  - name: ':tada: Production'
    description: '本番環境へのデプロイ'
    color: 'FBCA04'
  - name: ':rocket: Staging'
    description: 'ステージング環境へのデプロイ'
    color: 'D93F0B'
  - name: ':lipstick: Design'
    description: 'デザインのタスク'
    color: 'D4C5F9'
  - name: ':art: Frontend'
    description: 'フロントエンドのタスク'
    color: 'F9D0C4'
  - name: ':gear: Backend'
    description: 'バックエンドのタスク'
    color: 'C5DEF5'
  - name: ':hammer: Infrastructure'
    description: 'インフラのタスク'
    color: 'C2E0C6'
  - name: ':timer_clock: Story Points: 1'
    description: '4h以内に終わる作業'
    color: 'FEF2C0'
  - name: ':timer_clock: Story Points: 2'
    description: '8h以内に終わる作業'
    color: 'FEF2C0'
  - name: ':timer_clock: Story Points: 3'
    description: '12h以内に終わる作業'
    color: 'FEF2C0'
  - name: ':timer_clock: Story Points: 5'
    description: '20h以内に終わる作業'
    color: 'FEF2C0'
  - name: ':timer_clock: Story Points: 8'
    description: '32h以内に終わる作業'
    color: 'FEF2C0'
  - name: ':timer_clock: Story Points: Over 8'
    description: '32h以上かかる作業'
    color: 'FEF2C0'
  - name: ':rotating_light: Priority: Urgent'
    description: '緊急の対応が必要なタスク'
    color: 'B60205'
  - name: ':leopard: Priority: High'
    description: '優先度の高いタスク'
    color: 'FBCA04'
  - name: ':rabbit: Priority: Medium'
    description: '優先度が中程度のタスク'
    color: 'D93F0B'
  - name: ':turtle: Priority: Low'
    description: '優先度の低いタスク'
    color: '0E8A16'
