labels:
  - name: ':robot: Renovate'
    description: 'Renovate による依存関係の更新'
    color: '0052CC'
    id: 8696094261
  - name: ':tada: Production'
    description: '本番環境へのデプロイ'
    color: 'FBCA04'
    id: 8696094276
  - name: ':rocket: Staging'
    description: 'ステージング環境へのデプロイ'
    color: 'D93F0B'
    id: 8696094296
  - name: ':lipstick: Design'
    description: 'デザインのタスク'
    color: 'D4C5F9'
    id: 8696094313
  - name: ':art: Frontend'
    description: 'フロントエンドのタスク'
    color: 'F9D0C4'
    id: 8696094325
  - name: ':gear: Backend'
    description: 'バックエンドのタスク'
    color: 'C5DEF5'
    id: 8696094345
  - name: ':hammer: Infrastructure'
    description: 'インフラのタスク'
    color: 'C2E0C6'
    id: 8696094359
  - name: ':timer_clock: Story Points: 1'
    description: '4h以内に終わる作業'
    color: 'FEF2C0'
    id: 8696094379
  - name: ':timer_clock: Story Points: 2'
    description: '8h以内に終わる作業'
    color: 'FEF2C0'
    id: 8696094408
  - name: ':timer_clock: Story Points: 3'
    description: '12h以内に終わる作業'
    color: 'FEF2C0'
    id: 8696094440
  - name: ':timer_clock: Story Points: 5'
    description: '20h以内に終わる作業'
    color: 'FEF2C0'
    id: 8696094460
  - name: ':timer_clock: Story Points: 8'
    description: '32h以内に終わる作業'
    color: 'FEF2C0'
    id: 8696094476
  - name: ':timer_clock: Story Points: Over 8'
    description: '32h以上かかる作業'
    color: 'FEF2C0'
    id: 8696094498
  - name: ':rotating_light: Priority: Urgent'
    description: '緊急の対応が必要なタスク'
    color: 'B60205'
    id: 8696094509
  - name: ':leopard: Priority: High'
    description: '優先度の高いタスク'
    color: 'FBCA04'
    id: 8696094518
  - name: ':rabbit: Priority: Medium'
    description: '優先度が中程度のタスク'
    color: 'D93F0B'
    id: 8696094541
  - name: ':turtle: Priority: Low'
    description: '優先度の低いタスク'
    color: '0E8A16'
    id: 8696094574
