$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
language: en
allowCompoundWords: true
useGitignore: true
words:
  - adipiscing
  - amet
  - eiusmod
  - elit
  - embla
  - guidlines
  - incididunt
  - Kaneko
  - kryota
  - noarchive
  - noto
  - Ryota
  - tempor
  - vitest
ignorePaths:
  - package.json
  - pnpm-lock.yaml
  - .vscode/
  - .*/
