name: Setup Playwright
description: Setup Playwright browsers

runs:
  using: 'composite'
  steps:
    - name: 🎱 Store Playwright's version
      id: playwright-version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(pnpm -s dlx playwright --version | sed 's/Version //')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT

    - name: 📦 Cache Playwright
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}

    - name: 🌐 Install Playwright browsers
      shell: bash
      run: pnpm exec playwright install --with-deps
