name: ✨ Check Quality

on:
  pull_request:
    branches:
      - main
      - develop
  # merge_group:
  #   branches:
  #     - main
  #     - develop
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    name: ♻️ Static Code Analysis
    runs-on: ubuntu-24.04

    steps:
      - name: ᛘ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: 🔨 Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: ✨ Quality check
        run: pnpm quality:check

  test-unit:
    name: ⚡️ Vitest (🧪 Unit / 🎨 Storybook)
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: ᛘ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: 🔨 Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: 🎱 Store Playwright's version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(pnpm -s dlx playwright --version | sed 's/Version //')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT

      - name: 📦 Cache Playwright
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ steps.playwright-version.outputs.version }}

      - name: 🌐 Install Playwright
        run: pnpm exec playwright install --with-deps

      - name: ⚡️ Vitest
        run: pnpm test-coverage

      - name: 📝 Create coverage report
        if: ${{ github.event_name == 'pull_request' }}
        uses: davelosert/vitest-coverage-report-action@8ab049ff5a2c6e78f78af446329379b318544a1a # v2.8.3
        with:
          json-summary-path: .vitest/coverage-summary.json
          json-final-path: .vitest/coverage-final.json
