name: ✨ Check Quality

on:
  pull_request:
    branches:
      - main
      - develop
  # merge_group:
  #   branches:
  #     - main
  #     - develop
  push:
    branches:
      - main
      - develop
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    name: ♻️ Static Code Analysis
    runs-on: ubuntu-24.04

    steps:
      - name: ᛘ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: 🔨 Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: ✨ Quality check
        run: pnpm quality:check

  test-unit:
    name: 🧪 Unit Test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: ᛘ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: 🔨 Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: ✅ Vitest
        run: pnpm test:unit-coverage

      - name: 📝 Create coverage report
        if: ${{ github.event_name == 'pull_request' }}
        uses: davelosert/vitest-coverage-report-action@8ab049ff5a2c6e78f78af446329379b318544a1a # v2.8.3
        with:
          json-summary-path: .vitest/coverage-summary.json
          json-final-path: .vitest/coverage-final.json

  test-storybook:
    name: 🧪 Storybook Test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: ᛘ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: 🔨 Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: 📦 Cache Playwright
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: 🌐 Install Playwright
        run: pnpm exec playwright install --with-deps

      - name: 🧪 Storybook Test
        run: pnpm test:storybook
