name: ✨ Check Quality

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    name: ♻️ Static Code Analysis
    runs-on: ubuntu-24.04

    steps:
      - name: ᛘ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref}}

      - name: 🔨 Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: ✨ Quality check
        run: pnpm quality:check

  test:
    name: 🧪 Unit Test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: ᛘ Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref}}

      - name: 🔨 Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: ✅ Vitest
        run: pnpm test:coverage

      - name: 📝 Create coverage report
        uses: davelosert/vitest-coverage-report-action@v2
